local M = {}

---@param colors CarbonPalette
---@param config CarbonConfig
function M.setup(colors, config)
  local theme = {}

  theme.highlights = {
    -- Editor
    ColorColumn = { bg = colors.cursor_line_bg },
    Conceal = { fg = colors.comment },
    CurSearch = { bg = colors.search, fg = colors.bg },
    Cursor = { fg = colors.bg, bg = colors.cursor or colors.fg },
    lCursor = { fg = colors.bg, bg = colors.cursor or colors.fg },
    CursorIM = { fg = colors.bg, bg = colors.cursor or colors.fg },
    CursorColumn = { bg = colors.cursor_line_bg },
    CursorLine = { bg = colors.cursor_line_bg },
    CursorLineNr = { fg = colors.cursor_line_fg },
    Directory = { fg = colors.link },
    DiffAdd = { bg = colors.diff_add_bg },
    DiffChange = { bg = colors.cursor_line_bg },
    DiffDelete = { bg = colors.diff_remove_bg, fg = colors.diff_delete },
    DiffText = { bg = colors.diff_remove_bg, fg = colors.diff_delete },
    EndOfBuffer = { fg = colors.bg },
    ErrorMsg = { bg = colors.gutter, fg = colors.error },
    VertSplit = { fg = colors.gutter, bg = colors.border },
    WinSeparator = { fg = colors.win_separator, bg = colors.none },
    Folded = { fg = colors.comment, bg = colors.cursor_line_bg },
    FoldColumn = { fg = colors.comment, bg = colors.gutter },
    SignColumn = { fg = colors.link, bg = colors.gutter },
    IncSearch = { bg = colors.search },
    Substitute = { bg = colors.search, fg = colors.bg },
    LineNr = { fg = colors.line_nr, bg = colors.gutter },
    LineNrAbove = { fg = colors.line_nr },
    LineNrBelow = { fg = colors.line_nr },
    MatchParen = { fg = colors.func, bg = colors.border },
    ModeMsg = { fg = colors.fg, bold = true },
    MsgArea = { fg = colors.fg },
    MoreMsg = { fg = colors.cursor_line_fg },
    NonText = { fg = colors.comment },
    Normal = { fg = colors.fg, bg = config.transparent and colors.none or colors.bg },
    NormalFloat = { fg = colors.fg, bg = colors.cursor_line_bg },
    FloatBorder = { fg = colors.border, bg = colors.cursor_line_bg },
    FloatTitle = { fg = colors.identifier, bg = colors.cursor_line_bg },
    NormalNC = { fg = config.dim_inactive and (colors.fg_dark or colors.comment) or colors.fg, bg = config.transparent and colors.none or (config.dim_inactive and (colors.bg_dark or colors.bg) or colors.bg) },
    Pmenu = { fg = colors.pmenu_fg, bg = colors.pmenu_bg },
    PmenuSel = { fg = colors.pmenu_sel_fg, bg = colors.pmenu_sel_bg },
    PmenuSbar = { bg = colors.cursor_line_bg },
    PmenuThumb = { bg = colors.border },
    Question = { fg = colors.cursor_line_fg },
    QuickFixLine = { bg = colors.cursor_line_bg, bold = true },
    Search = { bg = colors.search },
    SpecialKey = { fg = colors.link },
    SpellBad = { sp = colors.error, undercurl = true },
    SpellCap = { sp = colors.warning, undercurl = true },
    SpellLocal = { sp = colors.info, undercurl = true },
    SpellRare = { sp = colors.hint, undercurl = true },
    StatusLine = { fg = colors.fg, bg = colors.bg },
    StatusLineNC = { fg = colors.comment, bg = colors.bg },
    TabLine = { fg = colors.comment, bg = colors.cursor_line_bg },
    TabLineFill = { bg = colors.bg },
    TabLineSel = { fg = colors.fg, bg = colors.bg },
    Title = { fg = colors.identifier, bold = true },
    Visual = { bg = colors.selection },
    VisualNOS = { bg = colors.selection },
    WarningMsg = { fg = colors.warning },
    Whitespace = { fg = colors.comment },
    WildMenu = { fg = colors.comment, bg = colors.cursor_line_bg },
    WinBar = { link = "StatusLine" },
    WinBarNC = { link = "StatusLineNC" },

    -- Syntax (matching IntelliJ Carbon theme)
    Comment = { fg = colors.comment, italic = config.styles.comments.italic },
    Constant = { fg = colors.constant or colors.variable },
    String = { fg = colors.string },
    Character = { fg = colors.string },
    Number = { fg = colors.number },
    Boolean = { fg = colors.keyword },
    Float = { fg = colors.number },

    Identifier = { fg = colors.identifier },
    Function = vim.tbl_extend("force", { fg = colors.func }, config.styles.functions),

    Statement = { fg = colors.keyword },
    Conditional = { fg = colors.keyword },
    Repeat = { fg = colors.keyword },
    Label = { fg = colors.info },
    Operator = { fg = colors.keyword },
    Keyword = { fg = colors.keyword },
    Exception = { fg = colors.keyword },

    PreProc = { fg = colors.keyword },
    Include = { fg = colors.keyword },
    Define = { fg = colors.keyword },
    Macro = { fg = colors.func },
    PreCondit = { fg = colors.keyword },

    Type = { fg = colors.string },
    StorageClass = { fg = colors.keyword },
    Structure = { fg = colors.keyword },
    Typedef = { fg = colors.string },

    Special = { fg = colors.identifier },
    SpecialChar = { fg = colors.string },
    Tag = { fg = colors.html_tag },
    Delimiter = { fg = colors.bracket or colors.fg },
    SpecialComment = { fg = colors.comment },
    Debug = { fg = colors.warning },

    Underlined = { fg = colors.link, underline = true },
    Ignore = { fg = colors.html_attr_alt, bg = colors.gutter, bold = true },
    Error = { bg = colors.diff_remove_bg },
    Todo = { fg = colors.html_attr_alt, bg = colors.gutter, bold = true },

    -- Diagnostics
    DiagnosticError = { fg = colors.error },
    DiagnosticWarn = { fg = colors.warning },
    DiagnosticInfo = { fg = colors.info },
    DiagnosticHint = { fg = colors.hint },
    DiagnosticOk = { fg = colors.git_add },

    DiagnosticVirtualTextError = { fg = colors.error, bg = colors.diff_remove_bg },
    DiagnosticVirtualTextWarn = { fg = colors.warning, bg = colors.diff_change_bg },
    DiagnosticVirtualTextInfo = { fg = colors.info, bg = colors.cursor_line_bg },
    DiagnosticVirtualTextHint = { fg = colors.hint, bg = colors.cursor_line_bg },
    DiagnosticVirtualTextOk = { fg = colors.git_add, bg = colors.diff_add_bg },

    DiagnosticUnderlineError = { sp = colors.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = colors.warning, undercurl = true },
    DiagnosticUnderlineInfo = { sp = colors.info, undercurl = true },
    DiagnosticUnderlineHint = { sp = colors.hint, undercurl = true },
    DiagnosticUnderlineOk = { sp = colors.git_add, undercurl = true },

    DiagnosticFloatingError = { fg = colors.error },
    DiagnosticFloatingWarn = { fg = colors.warning },
    DiagnosticFloatingInfo = { fg = colors.info },
    DiagnosticFloatingHint = { fg = colors.hint },
    DiagnosticFloatingOk = { fg = colors.git_add },

    DiagnosticSignError = { fg = colors.error },
    DiagnosticSignWarn = { fg = colors.warning },
    DiagnosticSignInfo = { fg = colors.info },
    DiagnosticSignHint = { fg = colors.hint },
    DiagnosticSignOk = { fg = colors.git_add },

    -- LSP
    LspReferenceText = { bg = colors.cursor_line_bg },
    LspReferenceRead = { bg = colors.cursor_line_bg },
    LspReferenceWrite = { bg = colors.cursor_line_bg },
    LspSignatureActiveParameter = { bg = colors.cursor_line_bg, bold = true },
    LspCodeLens = { fg = colors.comment },
    LspCodeLensSeparator = { fg = colors.border },
    LspInlayHint = { fg = colors.comment, bg = colors.cursor_line_bg },

    -- Treesitter
    ["@attribute"] = { fg = colors.html_tag },
    ["@boolean"] = { fg = colors.keyword },
    ["@character"] = { fg = colors.string },
    ["@character.special"] = { fg = colors.identifier },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = colors.string },
    ["@comment.error"] = { fg = colors.error },
    ["@comment.note"] = { fg = colors.info },
    ["@comment.todo"] = { fg = colors.html_tag, bold = true },
    ["@comment.warning"] = { fg = colors.warning },
    ["@constant"] = { fg = colors.constant or colors.variable },
    ["@constant.builtin"] = { fg = colors.keyword },
    ["@constant.macro"] = { fg = colors.constant or colors.variable },
    ["@constructor"] = { fg = colors.identifier },
    ["@diff.delta"] = { fg = colors.git_change },
    ["@diff.minus"] = { fg = colors.git_delete },
    ["@diff.plus"] = { fg = colors.git_add },
    ["@function"] = vim.tbl_extend("force", { fg = colors.func }, config.styles.functions),
    ["@function.builtin"] = vim.tbl_extend("force", { fg = colors.func }, config.styles.functions),
    ["@function.call"] = vim.tbl_extend("force", { fg = colors.func }, config.styles.functions),
    ["@function.macro"] = vim.tbl_extend("force", { fg = colors.func }, config.styles.functions),
    ["@function.method"] = vim.tbl_extend("force", { fg = colors.func }, config.styles.functions),
    ["@function.method.call"] = vim.tbl_extend("force", { fg = colors.func }, config.styles.functions),
    ["@keyword"] = { fg = colors.keyword },
    ["@keyword.conditional"] = { fg = colors.keyword },
    ["@keyword.conditional.ternary"] = { fg = colors.keyword },
    ["@keyword.coroutine"] = { fg = colors.keyword },
    ["@keyword.debug"] = { fg = colors.warning },
    ["@keyword.directive"] = { fg = colors.keyword },
    ["@keyword.directive.define"] = { fg = colors.keyword },
    ["@keyword.exception"] = { fg = colors.keyword },
    ["@keyword.function"] = { fg = colors.keyword },
    ["@keyword.import"] = { fg = colors.keyword },
    ["@keyword.modifier"] = { fg = colors.keyword },
    ["@keyword.operator"] = { fg = colors.keyword },
    ["@keyword.repeat"] = { fg = colors.keyword },
    ["@keyword.return"] = { fg = colors.keyword },
    ["@keyword.storage"] = { fg = colors.keyword },
    ["@keyword.type"] = { fg = colors.keyword },
    ["@label"] = { fg = colors.info },
    ["@markup.emphasis"] = { italic = true },
    ["@markup.heading"] = { fg = colors.identifier, bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = colors.link },
    ["@markup.link.label"] = { fg = colors.link },
    ["@markup.link.url"] = { fg = colors.link, underline = true },
    ["@markup.list"] = { fg = colors.html_tag },
    ["@markup.list.checked"] = { fg = colors.git_add },
    ["@markup.list.unchecked"] = { fg = colors.comment },
    ["@markup.math"] = { fg = colors.number },
    ["@markup.quote"] = { fg = colors.comment, italic = true },
    ["@markup.raw"] = { fg = colors.string_literal_fg },
    ["@markup.raw.block"] = { fg = colors.string_literal_fg },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { fg = colors.class },
    ["@module.builtin"] = { fg = colors.keyword },
    ["@namespace"] = { fg = colors.class },
    ["@none"] = {},
    ["@number"] = { fg = colors.number },
    ["@number.float"] = { fg = colors.number },
    ["@operator"] = { fg = colors.info },
    ["@property"] = vim.tbl_extend("force", { fg = colors.html_attr }, config.styles.properties),
    ["@punctuation.bracket"] = { fg = colors.bracket or colors.fg },
    ["@punctuation.delimiter"] = { fg = colors.bracket or colors.fg },
    ["@punctuation.special"] = { fg = colors.info },
    ["@string"] = { fg = colors.string },
    ["@string.documentation"] = { fg = colors.string },
    ["@string.escape"] = { fg = colors.identifier },
    ["@string.regexp"] = { fg = colors.html_tag },
    ["@string.special"] = { fg = colors.string_literal_fg },
    ["@string.special.path"] = { fg = colors.link },
    ["@string.special.symbol"] = { fg = colors.variable },
    ["@string.special.url"] = { fg = colors.link, underline = true },
    ["@tag"] = { fg = colors.html_tag },
    ["@tag.attribute"] = { fg = colors.html_attr },
    ["@tag.builtin"] = { fg = colors.html_tag },
    ["@tag.delimiter"] = { fg = colors.comment },
    ["@type"] = { fg = colors.string },
    ["@type.builtin"] = { fg = colors.info },
    ["@type.definition"] = { fg = colors.string },
    ["@type.qualifier"] = { fg = colors.keyword },
    ["@variable"] = { fg = colors.fg },
    ["@variable.builtin"] = { fg = colors.keyword },
    ["@variable.member"] = { fg = colors.html_attr },
    ["@variable.parameter"] = { fg = colors.parameter },
    ["@variable.parameter.builtin"] = { fg = colors.parameter },

    -- Language-specific Treesitter overrides
    ["@constructor.lua"] = { fg = colors.class },
    ["@constructor.tsx"] = { fg = colors.info },
    ["@constructor.javascript"] = { fg = colors.info },
    ["@tag.tsx"] = { fg = colors.keyword },
    ["@tag.javascript"] = { fg = colors.keyword },
    ["@tag.delimiter.tsx"] = { fg = colors.comment },
    ["@punctuation.special.markdown"] = { fg = colors.html_tag },
    ["@markup.list.markdown"] = { fg = colors.html_tag, bold = true },
    ["@markup.raw.markdown_inline"] = { fg = colors.info, bg = colors.cursor_line_bg },

    -- LSP Semantic Tokens
    ["@lsp.type.boolean"] = { link = "@boolean" },
    ["@lsp.type.builtinType"] = { link = "@type.builtin" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.deriveHelper"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
    ["@lsp.type.formatSpecifier"] = { link = "@markup.list" },
    ["@lsp.type.generic"] = { link = "@variable" },
    ["@lsp.type.interface"] = { fg = colors.class },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.lifetime"] = { link = "@keyword.storage" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.namespace.python"] = { link = "@variable" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
    ["@lsp.type.selfTypeKeyword"] = { link = "@variable.builtin" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.typeAlias"] = { link = "@type.definition" },
    ["@lsp.type.unresolvedReference"] = { sp = colors.error, undercurl = true },
    ["@lsp.type.variable"] = {},
    ["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.keyword.async"] = { link = "@keyword.coroutine" },
    ["@lsp.typemod.keyword.injected"] = { link = "@keyword" },
    ["@lsp.typemod.macro.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.operator.injected"] = { link = "@operator" },
    ["@lsp.typemod.string.injected"] = { link = "@string" },
    ["@lsp.typemod.struct.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.type.defaultLibrary"] = { fg = colors.info },
    ["@lsp.typemod.typeAlias.defaultLibrary"] = { fg = colors.info },
    ["@lsp.typemod.variable.callable"] = { link = "@function" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.injected"] = { link = "@variable" },
    ["@lsp.typemod.variable.static"] = { link = "@constant" },

    -- Git Signs
    GitSignsAdd = { fg = colors.git_add },
    GitSignsChange = { fg = colors.git_change },
    GitSignsDelete = { fg = colors.git_delete },
    GitSignsAddNr = { fg = colors.git_add },
    GitSignsChangeNr = { fg = colors.git_change },
    GitSignsDeleteNr = { fg = colors.git_delete },
    GitSignsAddLn = { bg = colors.diff_add_bg },
    GitSignsChangeLn = { bg = colors.cursor_line_bg },
    GitSignsDeleteLn = { bg = colors.diff_remove_bg },
    GitSignsAddInline = { bg = colors.diff_add_bg },
    GitSignsChangeInline = { bg = colors.diff_change_bg },
    GitSignsDeleteInline = { bg = colors.diff_remove_bg },

    -- Signify (legacy)
    SignifySignAdd = { fg = colors.git_add, bg = colors.gutter, bold = true },
    SignifySignChange = { fg = colors.git_change, bg = colors.gutter, bold = true },
    SignifySignDelete = { fg = colors.git_delete, bg = colors.gutter, bold = true },
    SignifyLineAdd = { fg = colors.git_add, bg = colors.gutter, bold = true },
    SignifyLineChange = { fg = colors.git_change, bg = colors.gutter, bold = true },
    SignifyLineDelete = { fg = colors.git_delete, bg = colors.gutter, bold = true },

    -- Telescope
    TelescopeNormal = { fg = colors.fg, bg = colors.bg },
    TelescopeBorder = { fg = colors.border, bg = colors.bg },
    TelescopePromptNormal = { fg = colors.fg, bg = colors.cursor_line_bg },
    TelescopePromptBorder = { fg = colors.cursor_line_bg, bg = colors.cursor_line_bg },
    TelescopePromptTitle = { fg = colors.bg, bg = colors.keyword },
    TelescopePreviewTitle = { fg = colors.bg, bg = colors.git_add },
    TelescopeResultsTitle = { fg = colors.bg, bg = colors.info },
    TelescopeSelection = { bg = colors.cursor_line_bg },
    TelescopeSelectionCaret = { fg = colors.keyword },
    TelescopeMultiSelection = { bg = colors.selection },
    TelescopeMatching = { fg = colors.keyword, bold = true },
    TelescopePromptPrefix = { fg = colors.keyword },

    -- NvimTree
    NvimTreeNormal = { fg = colors.fg, bg = colors.bg },
    NvimTreeNormalNC = { fg = colors.fg, bg = colors.bg },
    NvimTreeRootFolder = { fg = colors.identifier, bold = true },
    NvimTreeFolderName = { fg = colors.link },
    NvimTreeFolderIcon = { fg = colors.link },
    NvimTreeEmptyFolderName = { fg = colors.comment },
    NvimTreeOpenedFolderName = { fg = colors.link },
    NvimTreeSymlink = { fg = colors.link },
    NvimTreeGitDirty = { fg = colors.git_change },
    NvimTreeGitNew = { fg = colors.git_add },
    NvimTreeGitDeleted = { fg = colors.git_delete },
    NvimTreeSpecialFile = { fg = colors.identifier },
    NvimTreeIndentMarker = { fg = colors.border },
    NvimTreeImageFile = { fg = colors.fg },
    NvimTreeOpenedFile = { bg = colors.cursor_line_bg },

    -- Neo-tree
    NeoTreeNormal = { fg = colors.fg, bg = colors.bg },
    NeoTreeNormalNC = { fg = colors.fg, bg = colors.bg },
    NeoTreeDimText = { fg = colors.comment },
    NeoTreeDirectoryName = { fg = colors.link },
    NeoTreeDirectoryIcon = { fg = colors.link },
    NeoTreeRootName = { fg = colors.identifier, bold = true },
    NeoTreeFileName = { fg = colors.fg },
    NeoTreeFileIcon = { fg = colors.fg },
    NeoTreeFileNameOpened = { fg = colors.identifier },
    NeoTreeIndentMarker = { fg = colors.border },
    NeoTreeGitAdded = { fg = colors.git_add },
    NeoTreeGitConflict = { fg = colors.warning },
    NeoTreeGitDeleted = { fg = colors.git_delete },
    NeoTreeGitIgnored = { fg = colors.comment },
    NeoTreeGitModified = { fg = colors.git_change },
    NeoTreeGitUnstaged = { fg = colors.git_change },
    NeoTreeGitUntracked = { fg = colors.git_add },
    NeoTreeGitStaged = { fg = colors.git_add },

    -- WhichKey
    WhichKey = { fg = colors.keyword },
    WhichKeyGroup = { fg = colors.info },
    WhichKeyDesc = { fg = colors.fg },
    WhichKeySeparator = { fg = colors.comment },
    WhichKeyFloat = { bg = colors.cursor_line_bg },
    WhichKeyBorder = { fg = colors.border, bg = colors.cursor_line_bg },
    WhichKeyValue = { fg = colors.comment },

    -- Indent Blankline
    IndentBlanklineChar = { fg = colors.border, nocombine = true },
    IndentBlanklineContextChar = { fg = colors.identifier, nocombine = true },
    IblIndent = { fg = colors.border, nocombine = true },
    IblScope = { fg = colors.identifier, nocombine = true },

    -- Notify
    NotifyERRORBorder = { fg = colors.error },
    NotifyWARNBorder = { fg = colors.warning },
    NotifyINFOBorder = { fg = colors.info },
    NotifyDEBUGBorder = { fg = colors.comment },
    NotifyTRACEBorder = { fg = colors.hint },
    NotifyERRORIcon = { fg = colors.error },
    NotifyWARNIcon = { fg = colors.warning },
    NotifyINFOIcon = { fg = colors.info },
    NotifyDEBUGIcon = { fg = colors.comment },
    NotifyTRACEIcon = { fg = colors.hint },
    NotifyERRORTitle = { fg = colors.error },
    NotifyWARNTitle = { fg = colors.warning },
    NotifyINFOTitle = { fg = colors.info },
    NotifyDEBUGTitle = { fg = colors.comment },
    NotifyTRACETitle = { fg = colors.hint },

    -- Cmp
    CmpItemAbbr = { fg = colors.fg },
    CmpItemAbbrDeprecated = { fg = colors.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = colors.keyword, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = colors.keyword, bold = true },
    CmpItemKind = { fg = colors.identifier },
    CmpItemMenu = { fg = colors.comment },
    CmpItemKindClass = { fg = colors.class },
    CmpItemKindColor = { fg = colors.string },
    CmpItemKindConstant = { fg = colors.variable },
    CmpItemKindConstructor = { fg = colors.class },
    CmpItemKindEnum = { fg = colors.string },
    CmpItemKindEnumMember = { fg = colors.variable },
    CmpItemKindEvent = { fg = colors.identifier },
    CmpItemKindField = { fg = colors.variable },
    CmpItemKindFile = { fg = colors.link },
    CmpItemKindFolder = { fg = colors.link },
    CmpItemKindFunction = { fg = colors.func },
    CmpItemKindInterface = { fg = colors.class },
    CmpItemKindKeyword = { fg = colors.keyword },
    CmpItemKindMethod = { fg = colors.func },
    CmpItemKindModule = { fg = colors.class },
    CmpItemKindOperator = { fg = colors.keyword },
    CmpItemKindProperty = { fg = colors.variable },
    CmpItemKindReference = { fg = colors.variable },
    CmpItemKindSnippet = { fg = colors.string_literal_fg },
    CmpItemKindStruct = { fg = colors.string },
    CmpItemKindText = { fg = colors.fg },
    CmpItemKindTypeParameter = { fg = colors.string },
    CmpItemKindUnit = { fg = colors.number },
    CmpItemKindValue = { fg = colors.number },
    CmpItemKindVariable = { fg = colors.identifier },

    -- Navic
    NavicIconsFile = { fg = colors.fg },
    NavicIconsModule = { fg = colors.class },
    NavicIconsNamespace = { fg = colors.class },
    NavicIconsPackage = { fg = colors.class },
    NavicIconsClass = { fg = colors.class },
    NavicIconsMethod = { fg = colors.func },
    NavicIconsProperty = { fg = colors.variable },
    NavicIconsField = { fg = colors.variable },
    NavicIconsConstructor = { fg = colors.class },
    NavicIconsEnum = { fg = colors.string },
    NavicIconsInterface = { fg = colors.class },
    NavicIconsFunction = { fg = colors.func },
    NavicIconsVariable = { fg = colors.identifier },
    NavicIconsConstant = { fg = colors.variable },
    NavicIconsString = { fg = colors.string },
    NavicIconsNumber = { fg = colors.number },
    NavicIconsBoolean = { fg = colors.keyword },
    NavicIconsArray = { fg = colors.class },
    NavicIconsObject = { fg = colors.class },
    NavicIconsKey = { fg = colors.keyword },
    NavicIconsNull = { fg = colors.keyword },
    NavicIconsEnumMember = { fg = colors.variable },
    NavicIconsStruct = { fg = colors.string },
    NavicIconsEvent = { fg = colors.identifier },
    NavicIconsOperator = { fg = colors.keyword },
    NavicIconsTypeParameter = { fg = colors.string },
    NavicText = { fg = colors.fg },
    NavicSeparator = { fg = colors.comment },

    -- Lazy
    LazyButton = { bg = colors.cursor_line_bg, fg = colors.fg },
    LazyButtonActive = { bg = colors.selection, fg = colors.fg, bold = true },
    LazyComment = { fg = colors.comment },
    LazyCommit = { fg = colors.comment },
    LazyCommitIssue = { fg = colors.link },
    LazyCommitScope = { italic = true },
    LazyCommitType = { fg = colors.identifier, bold = true },
    LazyDimmed = { fg = colors.comment },
    LazyDir = { fg = colors.link },
    LazyH1 = { bg = colors.keyword, fg = colors.bg, bold = true },
    LazyH2 = { fg = colors.identifier, bold = true },
    LazyLocal = { fg = colors.warning },
    LazyNoCond = { fg = colors.error },
    LazyNormal = { fg = colors.fg, bg = colors.bg },
    LazyProgressDone = { fg = colors.keyword },
    LazyProgressTodo = { fg = colors.comment },
    LazyProp = { fg = colors.variable },
    LazyReasonCmd = { fg = colors.string_literal_fg },
    LazyReasonEvent = { fg = colors.warning },
    LazyReasonFt = { fg = colors.string },
    LazyReasonImport = { fg = colors.identifier },
    LazyReasonKeys = { fg = colors.keyword },
    LazyReasonPlugin = { fg = colors.func },
    LazyReasonRequire = { fg = colors.link },
    LazyReasonRuntime = { fg = colors.class },
    LazyReasonSource = { fg = colors.variable },
    LazyReasonStart = { fg = colors.git_add },
    LazySpecial = { fg = colors.identifier },
    LazyTaskError = { fg = colors.error },
    LazyTaskOutput = { fg = colors.fg },
    LazyUrl = { fg = colors.link, underline = true },
    LazyValue = { fg = colors.string },

    -- Mason
    MasonNormal = { fg = colors.fg, bg = colors.bg },
    MasonHeader = { bg = colors.keyword, fg = colors.bg, bold = true },
    MasonHeaderSecondary = { bg = colors.info, fg = colors.bg, bold = true },
    MasonHighlight = { fg = colors.info },
    MasonHighlightBlock = { bg = colors.info, fg = colors.bg },
    MasonHighlightBlockBold = { bg = colors.info, fg = colors.bg, bold = true },
    MasonHighlightSecondary = { fg = colors.warning },
    MasonMuted = { fg = colors.comment },
    MasonMutedBlock = { bg = colors.cursor_line_bg, fg = colors.comment },

    -- Dashboard
    DashboardHeader = { fg = colors.keyword },
    DashboardCenter = { fg = colors.identifier },
    DashboardFooter = { fg = colors.comment },
    DashboardShortCut = { fg = colors.func },

    -- Alpha
    AlphaHeader = { fg = colors.keyword },
    AlphaButtons = { fg = colors.identifier },
    AlphaShortcut = { fg = colors.func },
    AlphaFooter = { fg = colors.comment },

    -- Leap
    LeapMatch = { fg = colors.search, bold = true },
    LeapLabelPrimary = { fg = colors.bg, bg = colors.keyword, bold = true },
    LeapLabelSecondary = { fg = colors.bg, bg = colors.info, bold = true },

    -- Flash
    FlashMatch = { fg = colors.fg, bg = colors.selection },
    FlashCurrent = { fg = colors.bg, bg = colors.search },
    FlashLabel = { fg = colors.bg, bg = colors.keyword, bold = true },
    FlashBackdrop = { fg = colors.comment },

    -- Trouble
    TroubleNormal = { fg = colors.fg, bg = colors.bg },
    TroubleText = { fg = colors.fg },
    TroubleCount = { fg = colors.identifier, bg = colors.cursor_line_bg },
    TroubleFile = { fg = colors.link },
    TroubleFoldIcon = { fg = colors.comment },
    TroubleLocation = { fg = colors.comment },
    TroublePreview = { bg = colors.cursor_line_bg },
    TroubleSource = { fg = colors.comment },

    -- Bufferline
    BufferLineFill = { bg = colors.bg },
    BufferLineBackground = { fg = colors.comment, bg = colors.bg },
    BufferLineBuffer = { fg = colors.comment, bg = colors.bg },
    BufferLineBufferSelected = { fg = colors.fg, bg = colors.cursor_line_bg, bold = true },
    BufferLineBufferVisible = { fg = colors.fg, bg = colors.bg },
    BufferLineCloseButton = { fg = colors.comment, bg = colors.bg },
    BufferLineCloseButtonSelected = { fg = colors.error, bg = colors.cursor_line_bg },
    BufferLineCloseButtonVisible = { fg = colors.comment, bg = colors.bg },
    BufferLineDiagnostic = { fg = colors.comment },
    BufferLineDiagnosticSelected = { fg = colors.fg },
    BufferLineDiagnosticVisible = { fg = colors.comment },
    BufferLineError = { fg = colors.error },
    BufferLineErrorDiagnostic = { fg = colors.error },
    BufferLineHint = { fg = colors.hint },
    BufferLineHintDiagnostic = { fg = colors.hint },
    BufferLineIndicatorSelected = { fg = colors.keyword },
    BufferLineInfo = { fg = colors.info },
    BufferLineInfoDiagnostic = { fg = colors.info },
    BufferLineModified = { fg = colors.git_change },
    BufferLineModifiedSelected = { fg = colors.git_change },
    BufferLineModifiedVisible = { fg = colors.git_change },
    BufferLineNumbers = { fg = colors.comment },
    BufferLineNumbersSelected = { fg = colors.keyword },
    BufferLineNumbersVisible = { fg = colors.comment },
    BufferLinePick = { fg = colors.keyword, bold = true },
    BufferLinePickSelected = { fg = colors.keyword, bg = colors.cursor_line_bg, bold = true },
    BufferLinePickVisible = { fg = colors.keyword, bold = true },
    BufferLineSeparator = { fg = colors.border },
    BufferLineSeparatorSelected = { fg = colors.border },
    BufferLineSeparatorVisible = { fg = colors.border },
    BufferLineTab = { fg = colors.comment, bg = colors.bg },
    BufferLineTabSelected = { fg = colors.fg, bg = colors.cursor_line_bg },
    BufferLineTabClose = { fg = colors.error },
    BufferLineWarning = { fg = colors.warning },
    BufferLineWarningDiagnostic = { fg = colors.warning },

    -- Mini
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { bg = colors.cursor_line_bg },
    MiniCursorwordCurrent = { bg = colors.cursor_line_bg },
    MiniIndentscopeSymbol = { fg = colors.identifier, nocombine = true },
    MiniIndentscopePrefix = { nocombine = true },
    MiniJump = { bg = colors.keyword, fg = colors.bg },
    MiniJump2dSpot = { fg = colors.keyword, bold = true, nocombine = true },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { fg = colors.comment },
    MiniStarterHeader = { fg = colors.keyword },
    MiniStarterInactive = { fg = colors.comment },
    MiniStarterItem = { fg = colors.fg },
    MiniStarterItemBullet = { fg = colors.border },
    MiniStarterItemPrefix = { fg = colors.warning },
    MiniStarterSection = { fg = colors.identifier },
    MiniStarterQuery = { fg = colors.info },
    MiniStatuslineDevinfo = { fg = colors.fg, bg = colors.cursor_line_bg },
    MiniStatuslineFileinfo = { fg = colors.fg, bg = colors.cursor_line_bg },
    MiniStatuslineFilename = { fg = colors.fg, bg = colors.cursor_line_bg },
    MiniStatuslineInactive = { fg = colors.comment, bg = colors.bg },
    MiniStatuslineModeCommand = { fg = colors.bg, bg = colors.identifier, bold = true },
    MiniStatuslineModeInsert = { fg = colors.bg, bg = colors.html_attr, bold = true },
    MiniStatuslineModeNormal = { fg = colors.bg, bg = colors.info, bold = true },
    MiniStatuslineModeOther = { fg = colors.bg, bg = colors.string, bold = true },
    MiniStatuslineModeReplace = { fg = colors.warning, bg = colors.diff_remove_bg, bold = true },
    MiniStatuslineModeVisual = { fg = colors.bg, bg = colors.html_tag, bold = true },
    MiniSurround = { bg = colors.warning, fg = colors.bg },
    MiniTablineCurrent = { fg = colors.fg, bg = colors.cursor_line_bg },
    MiniTablineFill = { bg = colors.bg },
    MiniTablineHidden = { fg = colors.comment, bg = colors.bg },
    MiniTablineModifiedCurrent = { fg = colors.git_change, bg = colors.cursor_line_bg },
    MiniTablineModifiedHidden = { fg = colors.git_change, bg = colors.bg },
    MiniTablineModifiedVisible = { fg = colors.git_change, bg = colors.bg },
    MiniTablineTabpagesection = { fg = colors.bg, bg = colors.keyword },
    MiniTablineVisible = { fg = colors.fg, bg = colors.bg },
    MiniTestEmphasis = { bold = true },
    MiniTestFail = { fg = colors.error, bold = true },
    MiniTestPass = { fg = colors.git_add, bold = true },
    MiniTrailspace = { bg = colors.error },

    -- Aerial
    AerialNormal = { fg = colors.fg, bg = colors.bg },
    AerialLine = { bg = colors.cursor_line_bg },
    AerialGuide = { fg = colors.border },

    -- Blink.cmp
    BlinkCmpMenu = { fg = colors.fg, bg = colors.cursor_line_bg },
    BlinkCmpMenuBorder = { fg = colors.border, bg = colors.cursor_line_bg },
    BlinkCmpMenuSelection = { bg = colors.selection, fg = colors.pmenu_sel_fg },
    BlinkCmpScrollBarThumb = { bg = colors.border },
    BlinkCmpScrollBarGutter = { bg = colors.cursor_line_bg },
    BlinkCmpLabel = { fg = colors.fg },
    BlinkCmpLabelDeprecated = { fg = colors.comment, strikethrough = true },
    BlinkCmpLabelMatch = { fg = colors.keyword, bold = true },
    BlinkCmpLabelDetail = { fg = colors.comment },
    BlinkCmpLabelDescription = { fg = colors.comment },
    BlinkCmpKind = { fg = colors.identifier },
    BlinkCmpKindClass = { fg = colors.class },
    BlinkCmpKindColor = { fg = colors.string },
    BlinkCmpKindConstant = { fg = colors.variable },
    BlinkCmpKindConstructor = { fg = colors.class },
    BlinkCmpKindEnum = { fg = colors.string },
    BlinkCmpKindEnumMember = { fg = colors.variable },
    BlinkCmpKindEvent = { fg = colors.identifier },
    BlinkCmpKindField = { fg = colors.variable },
    BlinkCmpKindFile = { fg = colors.link },
    BlinkCmpKindFolder = { fg = colors.link },
    BlinkCmpKindFunction = { fg = colors.func },
    BlinkCmpKindInterface = { fg = colors.class },
    BlinkCmpKindKeyword = { fg = colors.keyword },
    BlinkCmpKindMethod = { fg = colors.func },
    BlinkCmpKindModule = { fg = colors.class },
    BlinkCmpKindOperator = { fg = colors.keyword },
    BlinkCmpKindProperty = { fg = colors.variable },
    BlinkCmpKindReference = { fg = colors.variable },
    BlinkCmpKindSnippet = { fg = colors.string_literal_fg },
    BlinkCmpKindStruct = { fg = colors.string },
    BlinkCmpKindText = { fg = colors.fg },
    BlinkCmpKindTypeParameter = { fg = colors.string },
    BlinkCmpKindUnit = { fg = colors.number },
    BlinkCmpKindValue = { fg = colors.number },
    BlinkCmpKindVariable = { fg = colors.identifier },
    BlinkCmpGhostText = { fg = colors.comment },
    BlinkCmpDoc = { fg = colors.fg, bg = colors.cursor_line_bg },
    BlinkCmpDocBorder = { fg = colors.border, bg = colors.cursor_line_bg },
    BlinkCmpDocSeparator = { fg = colors.border, bg = colors.cursor_line_bg },
    BlinkCmpSignatureHelp = { fg = colors.fg, bg = colors.cursor_line_bg },
    BlinkCmpSignatureHelpBorder = { fg = colors.border, bg = colors.cursor_line_bg },
    BlinkCmpSignatureHelpActiveParameter = { bg = colors.selection },

    -- Neogit
    NeogitBranch = { fg = colors.identifier },
    NeogitBranchHead = { fg = colors.identifier, bold = true },
    NeogitRemote = { fg = colors.info },
    NeogitHunkHeader = { fg = colors.fg, bg = colors.cursor_line_bg },
    NeogitHunkHeaderHighlight = { fg = colors.identifier, bg = colors.selection },
    NeogitDiffContext = { bg = colors.bg },
    NeogitDiffContextHighlight = { bg = colors.cursor_line_bg },
    NeogitDiffAdd = { fg = colors.git_add, bg = colors.diff_add_bg },
    NeogitDiffAddHighlight = { fg = colors.git_add, bg = colors.diff_add_bg },
    NeogitDiffDelete = { fg = colors.git_delete, bg = colors.diff_remove_bg },
    NeogitDiffDeleteHighlight = { fg = colors.git_delete, bg = colors.diff_remove_bg },
    NeogitDiffHeader = { fg = colors.identifier, bold = true },
    NeogitDiffHeaderHighlight = { fg = colors.identifier, bg = colors.selection, bold = true },
    NeogitCommitViewHeader = { fg = colors.identifier, bg = colors.cursor_line_bg },
    NeogitFilePath = { fg = colors.link },
    NeogitNotificationInfo = { fg = colors.info },
    NeogitNotificationWarning = { fg = colors.warning },
    NeogitNotificationError = { fg = colors.error },
    NeogitCursorLine = { bg = colors.cursor_line_bg },
    NeogitChangeModified = { fg = colors.git_change },
    NeogitChangeAdded = { fg = colors.git_add },
    NeogitChangeDeleted = { fg = colors.git_delete },
    NeogitChangeRenamed = { fg = colors.info },
    NeogitChangeCopied = { fg = colors.info },
    NeogitChangeUpdated = { fg = colors.git_change },
    NeogitChangeNewFile = { fg = colors.git_add },
    NeogitStagedChanges = { fg = colors.git_add, bold = true },
    NeogitUnstagedChanges = { fg = colors.git_change, bold = true },
    NeogitUntrackedFiles = { fg = colors.comment, bold = true },
    NeogitRecentCommits = { fg = colors.identifier, bold = true },
    NeogitSectionHeader = { fg = colors.identifier, bold = true },
    NeogitUnmergedInto = { fg = colors.keyword },
    NeogitUnpulledFrom = { fg = colors.keyword },
    NeogitObjectId = { fg = colors.comment },
    NeogitStash = { fg = colors.variable },
    NeogitRebaseDone = { fg = colors.git_add },
    NeogitTagName = { fg = colors.html_tag },
    NeogitTagDistance = { fg = colors.number },

    -- FZF-Lua
    FzfLuaNormal = { fg = colors.fg, bg = colors.bg },
    FzfLuaBorder = { fg = colors.border, bg = colors.bg },
    FzfLuaTitle = { fg = colors.identifier, bg = colors.bg },
    FzfLuaPreviewNormal = { fg = colors.fg, bg = colors.bg },
    FzfLuaPreviewBorder = { fg = colors.border, bg = colors.bg },
    FzfLuaPreviewTitle = { fg = colors.git_add, bg = colors.bg },
    FzfLuaCursor = { fg = colors.bg, bg = colors.fg },
    FzfLuaCursorLine = { bg = colors.cursor_line_bg },
    FzfLuaCursorLineNr = { fg = colors.cursor_line_fg },
    FzfLuaSearch = { fg = colors.bg, bg = colors.search },
    FzfLuaScrollBorderEmpty = { fg = colors.border },
    FzfLuaScrollBorderFull = { fg = colors.identifier },
    FzfLuaScrollFloatEmpty = { fg = colors.border },
    FzfLuaScrollFloatFull = { fg = colors.identifier },
    FzfLuaHelpNormal = { fg = colors.fg, bg = colors.cursor_line_bg },
    FzfLuaHelpBorder = { fg = colors.border, bg = colors.cursor_line_bg },
    FzfLuaHeaderBind = { fg = colors.keyword },
    FzfLuaHeaderText = { fg = colors.html_tag },
    FzfLuaPathColNr = { fg = colors.number },
    FzfLuaPathLineNr = { fg = colors.git_add },
    FzfLuaBufName = { fg = colors.identifier },
    FzfLuaBufNr = { fg = colors.number },
    FzfLuaBufFlagCur = { fg = colors.keyword },
    FzfLuaBufFlagAlt = { fg = colors.info },
    FzfLuaTabTitle = { fg = colors.identifier, bold = true },
    FzfLuaTabMarker = { fg = colors.keyword },
    FzfLuaLiveSym = { fg = colors.func },
    FzfLuaFzfNormal = { fg = colors.fg },
    FzfLuaFzfCursorLine = { bg = colors.cursor_line_bg },
    FzfLuaFzfMatch = { fg = colors.keyword, bold = true },
    FzfLuaFzfBorder = { fg = colors.border },
    FzfLuaFzfScrollbar = { fg = colors.identifier },
    FzfLuaFzfSeparator = { fg = colors.border },
    FzfLuaFzfGutter = { bg = colors.bg },
    FzfLuaFzfPointer = { fg = colors.keyword },
    FzfLuaFzfMarker = { fg = colors.keyword },
    FzfLuaFzfPrompt = { fg = colors.identifier },
    FzfLuaFzfQuery = { fg = colors.fg },
    FzfLuaDirIcon = { fg = colors.link },
    FzfLuaDirPart = { fg = colors.comment },

    -- Snacks.nvim
    SnacksNormal = { fg = colors.fg, bg = colors.bg },
    SnacksDashboardNormal = { fg = colors.fg, bg = colors.bg },
    SnacksDashboardDesc = { fg = colors.fg },
    SnacksDashboardFile = { fg = colors.link },
    SnacksDashboardDir = { fg = colors.comment },
    SnacksDashboardFooter = { fg = colors.comment },
    SnacksDashboardHeader = { fg = colors.keyword },
    SnacksDashboardIcon = { fg = colors.identifier },
    SnacksDashboardKey = { fg = colors.keyword },
    SnacksDashboardTerminal = { fg = colors.fg, bg = colors.bg },
    SnacksDashboardTitle = { fg = colors.identifier, bold = true },
    SnacksDashboardSpecial = { fg = colors.func },
    SnacksNotifierInfo = { fg = colors.info },
    SnacksNotifierWarn = { fg = colors.warning },
    SnacksNotifierError = { fg = colors.error },
    SnacksNotifierDebug = { fg = colors.comment },
    SnacksNotifierTrace = { fg = colors.hint },
    SnacksNotifierIconInfo = { fg = colors.info },
    SnacksNotifierIconWarn = { fg = colors.warning },
    SnacksNotifierIconError = { fg = colors.error },
    SnacksNotifierIconDebug = { fg = colors.comment },
    SnacksNotifierIconTrace = { fg = colors.hint },
    SnacksNotifierTitleInfo = { fg = colors.info },
    SnacksNotifierTitleWarn = { fg = colors.warning },
    SnacksNotifierTitleError = { fg = colors.error },
    SnacksNotifierTitleDebug = { fg = colors.comment },
    SnacksNotifierTitleTrace = { fg = colors.hint },
    SnacksNotifierBorderInfo = { fg = colors.info },
    SnacksNotifierBorderWarn = { fg = colors.warning },
    SnacksNotifierBorderError = { fg = colors.error },
    SnacksNotifierBorderDebug = { fg = colors.comment },
    SnacksNotifierBorderTrace = { fg = colors.hint },
    SnacksNotifierFooterInfo = { fg = colors.info },
    SnacksNotifierFooterWarn = { fg = colors.warning },
    SnacksNotifierFooterError = { fg = colors.error },
    SnacksNotifierFooterDebug = { fg = colors.comment },
    SnacksNotifierFooterTrace = { fg = colors.hint },
    SnacksInputNormal = { fg = colors.fg, bg = colors.cursor_line_bg },
    SnacksInputBorder = { fg = colors.border, bg = colors.cursor_line_bg },
    SnacksInputTitle = { fg = colors.identifier, bg = colors.cursor_line_bg },
    SnacksInputIcon = { fg = colors.identifier },
    SnacksInputPrompt = { fg = colors.identifier },
    SnacksScratchKey = { fg = colors.keyword },
    SnacksScratchDesc = { fg = colors.fg },
    SnacksProfilerIconInfo = { fg = colors.info },
    SnacksIndent = { fg = colors.border, nocombine = true },
    SnacksIndentScope = { fg = colors.identifier, nocombine = true },
    SnacksZenIcon = { fg = colors.identifier },
    SnacksPickerNormal = { fg = colors.fg, bg = colors.bg },
    SnacksPickerBorder = { fg = colors.border, bg = colors.bg },
    SnacksPickerTitle = { fg = colors.identifier, bg = colors.bg },
    SnacksPickerInputBorder = { fg = colors.html_tag, bg = colors.bg },
    SnacksPickerInputTitle = { fg = colors.html_tag, bg = colors.bg },
    SnacksPickerBoxTitle = { fg = colors.html_tag, bg = colors.bg },
    SnacksPickerPrompt = { fg = colors.identifier },
    SnacksPickerMatch = { fg = colors.keyword, bold = true },
    SnacksPickerSelected = { fg = colors.keyword },
    SnacksPickerUnselected = { fg = colors.comment },
    SnacksPickerToggle = { fg = colors.info, bg = colors.cursor_line_bg },
    SnacksPickerPickWinCurrent = { fg = colors.fg, bg = colors.identifier, bold = true },
    SnacksPickerPickWin = { fg = colors.fg, bg = colors.search, bold = true },
    SnacksPickerListCursorLine = { bg = colors.cursor_line_bg },
    SnacksPickerList = { fg = colors.fg, bg = colors.bg },
    SnacksPickerPreview = { fg = colors.fg, bg = colors.bg },
    SnacksPickerPreviewCursorLine = { bg = colors.cursor_line_bg },
    SnacksPickerDir = { fg = colors.comment },
    SnacksPickerFile = { fg = colors.fg },
    SnacksPickerCol = { fg = colors.number },
    SnacksPickerRow = { fg = colors.git_add },
    SnacksPickerComment = { fg = colors.comment },
    SnacksPickerLabel = { fg = colors.identifier },
    SnacksPickerIdx = { fg = colors.comment },
    SnacksPickerIcon = { fg = colors.identifier },
    SnacksPickerIconFile = { fg = colors.link },
    SnacksPickerIconDirectory = { fg = colors.link },
    SnacksPickerGitStatusAdded = { fg = colors.git_add },
    SnacksPickerGitStatusModified = { fg = colors.git_change },
    SnacksPickerGitStatusDeleted = { fg = colors.git_delete },
    SnacksPickerGitStatusRenamed = { fg = colors.info },
    SnacksPickerGitStatusUntracked = { fg = colors.git_add },
    SnacksPickerGitStatusIgnored = { fg = colors.comment },
    SnacksPickerDiagnosticError = { fg = colors.error },
    SnacksPickerDiagnosticWarn = { fg = colors.warning },
    SnacksPickerDiagnosticInfo = { fg = colors.info },
    SnacksPickerDiagnosticHint = { fg = colors.hint },

    -- Noice
    NoiceCmdlineIconInput = { fg = colors.html_tag },
    NoiceCmdlineIconLua = { fg = colors.info },
    NoiceCmdlinePopupBorderInput = { fg = colors.html_tag },
    NoiceCmdlinePopupBorderLua = { fg = colors.info },
    NoiceCmdlinePopupTitleInput = { fg = colors.html_tag },
    NoiceCmdlinePopupTitleLua = { fg = colors.info },
    NoiceCompletionItemKindDefault = { fg = colors.comment },

    -- Treesitter Context
    TreesitterContext = { bg = colors.cursor_line_bg },
    TreesitterContextLineNumber = { fg = colors.line_nr, bg = colors.cursor_line_bg },

    -- Render Markdown
    RenderMarkdownBullet = { fg = colors.html_tag },
    RenderMarkdownCode = { bg = colors.cursor_line_bg },
    RenderMarkdownCodeInline = { link = "@markup.raw.markdown_inline" },
    RenderMarkdownDash = { fg = colors.html_tag },
    RenderMarkdownTableHead = { fg = colors.keyword },
    RenderMarkdownTableRow = { fg = colors.html_tag },
    RenderMarkdownH1Bg = { bg = colors.diff_remove_bg },
    RenderMarkdownH1Fg = { fg = colors.keyword, bold = true },
    RenderMarkdownH2Bg = { bg = colors.diff_change_bg },
    RenderMarkdownH2Fg = { fg = colors.html_tag, bold = true },
    RenderMarkdownH3Bg = { bg = colors.diff_add_bg },
    RenderMarkdownH3Fg = { fg = colors.git_add, bold = true },
    RenderMarkdownH4Bg = { bg = colors.cursor_line_bg },
    RenderMarkdownH4Fg = { fg = colors.info, bold = true },
    RenderMarkdownH5Bg = { bg = colors.cursor_line_bg },
    RenderMarkdownH5Fg = { fg = colors.identifier, bold = true },
    RenderMarkdownH6Bg = { bg = colors.cursor_line_bg },
    RenderMarkdownH6Fg = { fg = colors.variable, bold = true },

    -- Rainbow Delimiters
    RainbowDelimiterRed = { fg = colors.keyword },
    RainbowDelimiterYellow = { fg = colors.html_tag },
    RainbowDelimiterBlue = { fg = colors.info },
    RainbowDelimiterOrange = { fg = colors.number },
    RainbowDelimiterGreen = { fg = colors.git_add },
    RainbowDelimiterViolet = { fg = colors.variable },
    RainbowDelimiterCyan = { fg = colors.string },

    -- Illuminate
    IlluminatedWordText = { bg = colors.cursor_line_bg },
    IlluminatedWordRead = { bg = colors.cursor_line_bg },
    IlluminatedWordWrite = { bg = colors.cursor_line_bg },

    -- Hop
    HopNextKey = { fg = colors.keyword, bold = true },
    HopNextKey1 = { fg = colors.info, bold = true },
    HopNextKey2 = { fg = colors.git_change },
    HopUnmatched = { fg = colors.comment },

    -- Language-specific (PHP)
    phpBacktick = { fg = colors.string_literal_fg, bg = colors.string_literal_bg },
    phpClasses = { fg = colors.class },
    phpDefine = { fg = colors.identifier },
    phpDocIdentifier = { fg = colors.variable },
    phpDocNamespaceSeparator = { fg = colors.class, bold = true },
    phpDocParam = { fg = colors.class },
    phpDocTags = { fg = colors.comment, bold = true },
    phpException = { fg = colors.string_literal_fg, bg = colors.string_literal_bg },
    phpFunctions = vim.tbl_extend("force", { fg = colors.func }, config.styles.functions),
    phpHereDoc = { fg = colors.string },
    phpIdentifier = { fg = colors.identifier },
    phpInclude = { fg = colors.keyword },
    phpKeyword = { fg = colors.keyword },
    phpMagicConstants = { fg = colors.variable },
    phpMemberSelector = { fg = colors.keyword },
    phpMethods = vim.tbl_extend("force", { fg = colors.func }, config.styles.functions),
    phpNowDoc = { fg = colors.string },
    phpOperator = { fg = colors.keyword },
    phpParent = { fg = colors.class },
    phpSpecialChar = { fg = colors.string },
    phpStaticClasses = { fg = colors.func },
    phpStructure = { fg = colors.keyword },
    phpType = { fg = colors.keyword },
    phpVarSelector = { fg = colors.identifier },

    -- Language-specific (HTML)
    htmlArg = { fg = colors.html_attr },
    htmlString = { fg = colors.string },
    htmlTag = { fg = colors.comment },
    htmlTagName = { fg = colors.html_tag },
    htmlValue = { fg = colors.string },

    -- Language-specific (CSS)
    cssProp = { fg = colors.html_attr_alt },

    -- Language-specific (JSON)
    jsonBoolean = { fg = colors.keyword },
    jsonKeyword = { fg = colors.class },

    -- DBG
    DbgCurrentLine = { fg = colors.diff_delete, bg = colors.diff_remove_bg },
    DbgCurrentSign = { fg = colors.diff_delete, bg = colors.diff_remove_bg },
    DbgBreakptLine = { bg = colors.git_add },
    DbgBreakptSign = { bg = colors.git_add },
    DbgCurrentStackPositionLine = { fg = colors.diff_change_bg },
    DbgCurrentStackPositionSign = { fg = colors.diff_change_bg },
  }

  -- Allow user customization
  config.on_highlights(theme.highlights, colors)

  return theme
end

return M
